# Generated by Django 5.2.3 on 2025-06-13 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
    ]
