# Generated by Django 5.2.3 on 2025-06-13 21:35

import django.db.models.deletion
from django.db import migrations, models

def create_default_category(apps, schema_editor):
    Category = apps.get_model('store', 'Category')
    # Create a default category
    Category.objects.create(name='Default Category')  # Adjust the name as needed

class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20250613_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='store.category')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category'),
        ),
        migrations.RunPython(create_default_category),  # Add the data migration
    ]